// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectVideoFile() {
  return window['go']['main']['App']['SelectVideoFile']();
}

export function StartCamera(arg1, arg2) {
  return window['go']['main']['App']['StartCamera'](arg1, arg2);
}

export function StopCamera(arg1) {
  return window['go']['main']['App']['StopCamera'](arg1);
}

export function SystemSetup(arg1) {
  return window['go']['main']['App']['SystemSetup'](arg1);
}
