// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelectVideoFile():Promise<string>;

export function StartCamera(arg1:string,arg2:string):Promise<void>;

export function StopCamera(arg1:string):Promise<void>;

export function SystemSetup(arg1:number):Promise<Array<string>>;
